---
blank_issues_enabled: false
contact_links:
  - name: App Development Part 3 Community Support
    url: https://github.com/developer-academy-unina/app-development-part-3/discussions
    about: Please ask and answer questions here.
